# Use an image with Python 3.11
FROM python:3.11-slim

# Install git and other system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    jq \
    libvips-dev \
    npm \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

# Create a non-root user
RUN groupadd -r agent_lens && useradd -r -g agent_lens agent_lens

# Upgrade pip
RUN pip install --upgrade pip

# Set the working directory
WORKDIR /app/

# Copy the repository to the image
COPY . .

# Set environment variables
ENV CLIP_CACHE=/app/.cache

# Create necessary directories and set permissions
RUN mkdir -p /app/logs /app/.cache && \
    chmod 777 /app /app/logs /app/.cache && \
    chown -R agent_lens:agent_lens /app /app/logs /app/.cache

# Add /app to the list of safe directories for Git
RUN git config --global --add safe.directory /app

# Remove all files matching .gitignore patterns and .git directory
RUN git clean -fdX && rm -rf .git

# Install the required Python packages
RUN pip install -r requirements.txt
RUN pip install fastapi hypha_rpc uvicorn .

# Switch to the non-root user
USER agent_lens

# Ensure the start script is executable
RUN chmod +x /app/scripts/docker_start.sh

# Entry point for the application
ENTRYPOINT ["/app/scripts/docker_start.sh"]